export const authConstant = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const dealConstants = {
    OPEN_DEAL_REQUEST: "OPEN_DEAL_REQUEST",
    OPEN_DEAL_SUCCESS: "OPEN_DEAL_SUCCESS",
    OPEN_DEAL_ERROR: "OPEN_DEAL_ERROR",

    GET_ALL_DEAL_REQUEST: "GET_ALL_DEAL_REQUEST",
    GET_ALL_DEAL_SUCCESS: "GET_ALL_DEAL_SUCCESS",
    GET_ALL_DEAL_ERROR: "GET_ALL_DEAL_ERROR",

    CLOSE_DEAL_REQUEST: "CLOSE_DEAL_REQUEST",
    CLOSE_DEAL_SUCCESS: "CLOSE_DEAL_SUCCESS",
    CLOSE_DEAL_ERROR: "CLOSE_DEAL_ERROR",
};

export const stocksConstants = {
    GET_STOCKS_REQUEST: "GET_STOCKS_REQUEST",
    GET_STOCKS_SUCCESS: "GET_STOCKS_SUCCESS",
    GET_STOCKS_ERROR: "GET_STOCKS_ERROR",
    FILTER_STOCKS: "FILTER_STOCKS",
};

export const forexConstants = {
    GET_FOREX_REQUEST: "GET_FOREX_REQUEST",
    GET_FOREX_SUCCESS: "GET_FOREX_SUCCESS",
    GET_FOREX_ERROR: "GET_FOREX_ERROR",
    FILTER_FOREXES: "FILTER_FOREXES",
};

export const cryptoConstants = {
    GET_CRYPTO_REQUEST: "GET_CRYPTO_REQUEST",
    GET_CRYPTO_SUCCESS: "GET_CRYPTO_SUCCESS",
    GET_CRYPTO_ERROR: "GET_CRYPTO_ERROR",
};
